"""empty message

Revision ID: 0c03bc8296c3
Revises: 2175a7719127
Create Date: 2019-06-17 17:20:35.095713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c03bc8296c3'
down_revision = '2175a7719127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picture_Title'), 'picture', ['Title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picture_Title'), table_name='picture')
    op.drop_table('picture')
    # ### end Alembic commands ###
