"""posts table

Revision ID: 2175a7719127
Revises: 97fc4efadb63
Create Date: 2019-06-17 11:11:13.114419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2175a7719127'
down_revision = '97fc4efadb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('photo', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'photo')
    # ### end Alembic commands ###
