"""empty message

Revision ID: 3f6c8513b1df
Revises: db45e670feec
Create Date: 2019-06-17 17:29:15.436733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6c8513b1df'
down_revision = 'db45e670feec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date')
    # ### end Alembic commands ###
