"""empty message

Revision ID: 97fc4efadb63
Revises: 
Create Date: 2019-06-16 09:44:35.170568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fc4efadb63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_Description'), 'post', ['Description'], unique=False)
    op.create_index(op.f('ix_post_Title'), 'post', ['Title'], unique=False)
    op.create_index(op.f('ix_post_post'), 'post', ['post'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_post'), table_name='post')
    op.drop_index(op.f('ix_post_Title'), table_name='post')
    op.drop_index(op.f('ix_post_Description'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
