"""empty message

Revision ID: db45e670feec
Revises: 0c03bc8296c3
Create Date: 2019-06-17 17:21:20.287273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db45e670feec'
down_revision = '0c03bc8296c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('photo', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'photo')
    # ### end Alembic commands ###
