"""empty message

Revision ID: f8cd4e260151
Revises: 3f6c8513b1df
Create Date: 2019-06-17 17:51:29.477443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cd4e260151'
down_revision = '3f6c8513b1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('date', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'date')
    # ### end Alembic commands ###
